apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-filehost-storedfiles
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/d/k8s/persistent_volume/filehost/storedfiles"
