apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite
  labels:
    component: graphite
spec:
  replicas: 1
  selector:
    matchLabels:
      component: graphite
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: graphite
    spec:
      containers:
        - name: graphite-statsd
          image: graphiteapp/graphite-statsd
          env:
            - name: GRAPHITE_LOG_FILE_INFO
              value: "-"
            - name: GRAPHITE_LOG_FILE_EXCEPTION
              value: "-"
            - name: GRAPHITE_LOG_FILE_CACHE
              value: "-"
            - name: GRAPHITE_LOG_FILE_RENDERING
              value: "-"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 80
            - containerPort: 8125
            - containerPort: 2003
            - containerPort: 2004
            - containerPort: 2023
            - containerPort: 2024
            - containerPort: 8125
              protocol: UDP
            - containerPort: 8126
          volumeMounts:
            - mountPath: "/opt/graphite/storage"
              name: graphite-storage
          resources:
            limits:
              memory: 400Mi
            requests:
              memory: 200Mi
      volumes:
        - name: graphite-storage
          persistentVolumeClaim:
            claimName: graphite-storage-pvc