apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      component: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        component: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.22.1
          command:
            - "/bin/prometheus"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=45d"
            - "--web.page-title=QPA Web - Prometheus"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: prometheus-storage
              mountPath: "/prometheus"
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-configmap
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-storage-pvc