apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qpa
  name: client
  labels:
    component: client
spec:
  replicas: 2
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
          image: gjani/laboschqpa-client:master
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 8
            periodSeconds: 4
          ports:
            - containerPort: 3000