apiVersion: v1
kind: Service
metadata:
  namespace: qpa
  name: imageconverter-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: imageconverter
  ports:
    - port: 4300
      targetPort: 4300
