apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
spec:
  containers:
    - name: dev-pod
      image: centos
      command:
        - "sh"
        - "-c"
      args:
        - "yum install -y nfs-utils nmap unzip wget java && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.2.zip && unzip apache-jmeter-5.2.zip && sleep 99999999"
      securityContext:
        privileged: true
