apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
spec:
  containers:
    - name: dev-pod
      image: centos
      command:
        - "sh"
        - "-c"
      args:
        - "yum install -y nfs-utils nmap; sleep 99999999"
      securityContext:
        privileged: true
