apiVersion: v1
kind: Service
metadata:
  name: client-nodeport-http
spec:
  type: NodePort
  selector:
    component: client
  ports:
  - name: http-client
    port: 3000
    targetPort: 3000
    nodePort: 30300