apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filehost-pvc-storedfiles
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi