apiVersion: apps/v1
kind: Deployment
metadata:
  name: filehost
  labels:
    component: filehost
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: filehost
  template:
    metadata:
      labels:
        component: filehost
    spec:
      securityContext:
        runAsUser: 10002
        runAsGroup: 10002
        fsGroup: 10003
      containers:
        - name: filehost
          image: gjani/laboschqpa-filehost
          ports:
            - containerPort: 4200
          volumeMounts:
          - mountPath: "/app/secret/"
            name: secrets
          - mountPath: "/srv/filehost/storedfiles/mnt1/"
            name: filehost-storedfiles
      volumes:
        - name: secrets
          secret:
            secretName: laboschqpa-filehost-secrets
        - name: filehost-storedfiles
          persistentVolumeClaim:
            claimName: filehost-pvc-storedfiles
