apiVersion: v1
kind: Service
metadata:
  name: filehost-nodeport-remotedebug
spec:
  type: NodePort
  selector:
    component: filehost
  ports:
  - name: remote-debug
    port: 30006
    targetPort: 30006
    nodePort: 30006