apiVersion: v1
kind: Service
metadata:
  name: filehost-nodeport-http
spec:
  type: NodePort
  selector:
    component: filehost
  ports:
  - name: http
    port: 4200
    targetPort: 4200
    nodePort: 30420