apiVersion: apps/v1
kind: Deployment
metadata:
  name: filehost
  labels:
    component: filehost
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: filehost
  template:
    metadata:
      labels:
        component: filehost
    spec:
      securityContext:
        fsGroup: 10002
      containers:
        - name: filehost
          image: gjani/laboschqpa-filehost
          command: ["java", "-jar", "-Dspring.profiles.active=k8s_dev",  "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:30006", "laboschqpa.filehost.jar"]
          ports:
            - containerPort: 4200
          volumeMounts:
            - mountPath: "/app/secret/"
              name: secrets
            - mountPath: "/srv/filehost/storedfiles/mnt1/"
              name: filehost-storedfiles
      volumes:
        - name: secrets
          secret:
            secretName: laboschqpa-filehost-secrets
        - name: filehost-storedfiles
          persistentVolumeClaim:
            claimName: filehost-pvc-storedfiles
