apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-http
spec:
  type: NodePort
  selector:
    component: frontend
  ports:
  - name: http-frontend
    port: 3000
    targetPort: 3000
    nodePort: 30300