apiVersion: v1
kind: Service
metadata:
  name: imageconverter-nodeport-http
spec:
  type: NodePort
  selector:
    component: imageconverter
  ports:
  - name: http
    port: 4300
    targetPort: 4300
    nodePort: 30430