apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    component: server
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: gjani/laboschcst-server
          ports:
            - containerPort: 8080
            - containerPort: 5005
          volumeMounts:
          - mountPath: "/app/secret/"
            name: secrets
      volumes:
        - name: secrets
          secret:
            secretName: laboschcst-server-secrets