apiVersion: v1
kind: Service
metadata:
  name: server-nodeport-remotedebug
spec:
  type: NodePort
  selector:
    component: server
  ports:
  - name: remote-debug
    port: 30005
    targetPort: 30005
    nodePort: 30005