apiVersion: v1
kind: Service
metadata:
  name: server-nodeport-http
spec:
  type: NodePort
  selector:
    component: server
  ports:
  - name: http-server
    port: 8080
    targetPort: 8080
    nodePort: 30080