apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
      annotations:
        prometheus.custom/enable_scrape: "true"
        prometheus.custom/scrape_port: "8080"
        prometheus.custom/metrics_path: "/actuator/prometheus"
    spec:
      containers:
        - name: server
          image: gjani/laboschqpa-server:master
          command: ["java", "-jar", "-Dspring.profiles.active=k8s_dev",  "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:30005", "laboschqpa.server.jar"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/app/secret/"
              name: secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: laboschqpa-server-secrets
