apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: csillagtura-sch-bme-hu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi