apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    component: grafana
  namespace: csillagtura-sch-bme-hu
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: grafana
      annotations:
        prometheus.custom/enable_scrape: "true"
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          env:
            - name: GF_PATHS_DATA
              value: "/run/storage/var/lib/grafana"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: "/run/storage/var/lib/grafana"
              name: grafana-data
          resources:
            limits:
              memory: 60Mi
            requests:
              memory: 30Mi
      volumes:
          - name: grafana-data
            persistentVolumeClaim:
              claimName: grafana-data-pvc