apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite
  labels:
    component: graphite
  namespace: csillagtura-sch-bme-hu
spec:
  replicas: 1
  selector:
    matchLabels:
      component: graphite
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: graphite
    spec:
      containers:
        - name: graphite-statsd
          image: graphiteapp/graphite-statsd
          env:
            - name: GRAPHITE_LOG_FILE_INFO
              value: "-"
            - name: GRAPHITE_LOG_FILE_EXCEPTION
              value: "-"
            - name: GRAPHITE_LOG_FILE_CACHE
              value: "-"
            - name: GRAPHITE_LOG_FILE_RENDERING
              value: "-"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 80
            - containerPort: 8125
            - containerPort: 2003
            - containerPort: 2004
            - containerPort: 2023
            - containerPort: 2024
            - containerPort: 8125
              protocol: UDP
            - containerPort: 8126
          volumeMounts:
            - name: graphite-storage
              mountPath: "/opt/graphite/storage"
            - name: graphite-conf
              mountPath: "/opt/graphite/conf/storage-aggregation.conf"
              subPath: "storage-aggregation.conf"
              readOnly: true
            - name: graphite-conf
              mountPath: "/opt/graphite/conf/storage-schemas.conf"
              subPath: "storage-schemas.conf"
              readOnly: true
          resources:
            limits:
              memory: 260Mi
            requests:
              memory: 220Mi
      volumes:
        - name: graphite-storage
          persistentVolumeClaim:
            claimName: graphite-storage-pvc
        - name: graphite-conf
          configMap:
            name: graphite-configmap-conf
