apiVersion: v1
kind: Service
metadata: 
  name: graphite-cluster-ip
  namespace: csillagtura-sch-bme-hu
spec:
  type: ClusterIP
  selector:
    component: graphite
  ports:
    - port: 80
      name: nginx
    - port: 2003
      name: carbon-receiver-plaintext
    - port: 2004
      name: carbon-receiver-pickle
    - port: 2023
      name: carbon-aggregator-plaintext
    - port: 2024
      name: carbon-aggregator-pickle
    - port: 8125
      protocol: UDP
      name: statsd
    - port: 8126
      name: statsd-admin
    