apiVersion: v1
kind: Service
metadata:
  name: prometheus-cluster-ip
  namespace: csillagtura-sch-bme-hu
spec:
  type: ClusterIP
  selector:
    component: prometheus
  ports:
    - port: 9090
      name: http
    