apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: grafana
  ports:
    - port: 3000
      targetPort: 3000
    