apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pick-up-some-image-variant-creation-jobs-cronjob
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 40
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: apicaller
              image: yauritux/busybox-curl
              args:
                - /bin/sh
                - -c
                - curl --max-time 8 -X POST http://filehost-cluster-ip:4200/api/internal/noAuth/imageVariant/pickUpSomeCreationJobs
          restartPolicy: Never
