apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pvc
spec:
# Uncomment these lines to use the HostPath PersistentVolume as storage for the nfs server
#  storageClassName: manual
#  volumeName: pv-volume-nfs-server
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi