apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pvc
spec:
  storageClassName: manual
  volumeName: pv-volume-nfs-server
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi