apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  namespace: cert-manager
  name: jenkins-schq-party-certificate
spec:
  secretName: jenkins-schq-party-tls-cert-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: jenkins.schq.party
  dnsNames:
    - jenkins.schq.party
