apiVersion: v1
kind: Service
metadata: 
  name: frontend-cluster-ip
  namespace: csillagtura-sch-bme-hu
spec:
  type: ClusterIP
  selector:
    component: frontend
  ports:
    - port: 3000
      targetPort: 80
