apiVersion: v1
kind: Service
metadata: 
  name: server-cluster-ip
  namespace: csillagtura-sch-bme-hu
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 8080
      targetPort: 8080
    