apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    component: server
  namespace: csillagtura-sch-bme-hu
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: gjani/laboschqpa-server:master
          command: ["java", "-XX:+PrintFlagsFinal", "-Xmx80m", "-jar", "-Dspring.profiles.active=kszk_staging", "laboschqpa.server.jar"]
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 8
            periodSeconds: 4
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/app/secret/"
              name: secrets
              readOnly: true
          resources:
            limits:
              memory: 420Mi
            requests:
              memory: 300Mi
      volumes:
        - name: secrets
          secret:
            secretName: laboschqpa-server-secrets
