apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/rewrite-target: /$1$2  # TODO: Turn this on, when react frontend is ready!
spec:
  rules:
    - http:
        paths:
            - path: /server/(.*)
#            - path: /?(server/)(.*)  # TODO: Turn this on, when react frontend is ready!
              backend:
                serviceName: server-cluster-ip
                servicePort: 8080
            - path: /?(.*)
#            - path: /?(.*)(.*)  # TODO: Turn this on, when react frontend is ready!
              backend:
                serviceName: frontend-cluster-ip
                servicePort: 3000