apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /?server/(.*)()
            pathType: Exact
            backend:
              service:
                name: server-cluster-ip
                port:
                  number: 8080
#          - path: /?(login/oauth2/code/)(.*)
#            backend:
#              serviceName: server-cluster-ip
#              servicePort: 8080

          - path: /?filehost/(.*)()
            pathType: Exact
            backend:
              service:
                name: filehost-cluster-ip
                port:
                  number: 4200

          - path: /?(.*)(.*)
            pathType: Exact
            backend:
              service:
                name: client-cluster-ip
                port:
                  number: 3000
    - host: grafana.local
      http:
        paths:
          - path: /?(.*)()
            pathType: Exact
            backend:
              service:
                name: grafana-cluster-ip
                port:
                  number: 3000
    - host: graphite.local
      http:
        paths:
          - path: /?(.*)()
            pathType: Exact
            backend:
              service:
                name: graphite-cluster-ip
                port:
                  number: 80
    - host: prometheus.local
      http:
        paths:
          - path: /?(.*)()
            pathType: Exact
            backend:
              service:
                name: prometheus-cluster-ip
                port:
                  number: 9090